spring:
  datasource:
    url: jdbc:postgresql://localhost/7_eleven_db
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
